### ISSUE TITLE
sx1262 modülünü rx ve tx modlarına alamıyorum. 

### ISSUE THREAD

**Issue by ademgolcuk42** [haluks/LoRa#1]
https://community.st.com/t5/stm32-mcus-wireless/issue-with-sx1262-module/m-p/736763#M21826 burada yaşadığım bir problemi paylaşmıştım. STM32f407vgt6 discovery bord kullanıyorum mikrodenetleyici olarak. Bu problem için çözüm üretebilir misiniz?

**Comment by haluks** [comment]
Merhaba,
Ebyte örnek bir dosya paylaşmış ve STM için yazılmış isterseniz onu da
inceleyin. Burada E22-400M30S_SX1268_LoRa_Module_
<https://www.cdebyte.com/products/E22-400M30S/4#Downloads> demo linki. STM
kullanmadım bazı şeyleri anlamamış olabilirim kusuruma bakmayın. Yazma ve
okuma fonksiyonlarında çok fazla parametre var öncelikle dikkatimi çeken o
oldu. SX için komutlar tek byte yani komut için komut boyutu girmeye gerek
yok. Bir de context nedir anlamadım. NSS pini SPI öncesi "0"
yapılacak context olarak bir parametreye ihtiyaç yok. Fonksiyonlarda ilk
olarak BUSSY  pinini kontrol edin sonra NSS pinin "0" yapın. Fonksiyonlar
doğru görünüyor sadece BUSSY kontrolünü yapmamışsınız.
Sizin bahsettiğiniz sorun okuma yazma fonksiyonlarından olamayabilir. Zaten
okuma ve yazma başarılı şekilde olmasa hata cevabını alamazdınız. Modülün
ilk başlatma düzeni çok önemli. Önceden ayarlanması gereken
konfigürasyonlar ve başlatma için gerekli bir sıralama var. Benim
kütüphanemde C ile yazılı siz isteseniz donanım kütüphanelerini STM için
düzenleyip olduğu gibi bu kütüphaneyi kullanabilirsiniz. SPI ve Pin
yönlendirmelerini değiştirmeniz yeterli olur. Daha fazla bir şey
söyleyebilmek için SX dosyanızı görmem gerekir.
İyi çalışmalar.

ademgolcuk42 ***@***.***>, 2 Kas 2024 Cmt, 14:06 tarihinde
şunu yazdı:

**Comment by ademgolcuk42** [comment]
Merhaba Haluk bey. ilginiz için çok teşekkür ederim öncelikle. Ben sx1262 lora modülünü kontrol etmek için semtechin github üzerinden yayınladığı kütüphaneyi (https://github.com/Lora-net/sx126x_driver) kullanmaya çalışıyorum. Tek bir write ve read fonksiyonlarıyla tüm modülü kontrol edebilmek için komut ve data parametrelerini birleştirilmiş o yüzden parametre sayısı fazla gözüküyor. context ifadesini de spi haberleşmesindeki pinleri tanımlayan bir structer olarak kullanıyorum.  SPI haberleşmesinde bir problem olduğunu ben de düşünmüyorum. Aşağıdaki kodlarla syncWord registerlerina 7 byte veri yazıp okuyabiliyorum problemsiz bir şekilde.

          sayac++;
	  sendData[0]=sayac;
	  sendData[1]=sayac>>8;
	  sendData[2]=sayac>>16;
	  sendData[3]=sayac>>24;


	  LoraInit();

	  for(int i=0;i<=7;i++)
		  sendData[i]=sayac+i;
	  sx126x_write_register(&myLoRa, 0x06C0, sendData, 7);
	  sx126x_read_register(&myLoRa, 0x06C0, readData, 7);


Aşağıda hazırladığım init dosyasını paylaşıyorum. Sizin hazırladığınız kütüphaneyi de detaylı incelemeye çalıştım ve sizin verdiğiniz değerleri vermeye çalıştım. modul_IO(); fonksiyonunun amacını tam anlayamadım.

void LoraInit()
{
    /* Reset işlemi */
		sx126x_reset(&myLoRa);
		sx126x_get_busy(&myLoRa);
    /* Wakeup */
		sx126x_wakeup(&myLoRa);
		sx126x_get_busy(&myLoRa);

    /* Standby moduna geç (STDBY_RC) */
		sx126x_set_standby(&myLoRa, SX126X_STANDBY_CFG_RC);
		sx126x_get_busy(&myLoRa);

	/* Regülatör modu ayarlama */
		sx126x_set_reg_mode(&myLoRa, SX126X_REG_MODE_DCDC);
		sx126x_get_busy(&myLoRa);


	/* RF frekansını ayarla */
		drmFrekans		=sx126x_set_rf_freq(&myLoRa, 868000000);
		sx126x_get_busy(&myLoRa);

    /* Paket tipini LoRa olarak ayarla */
		drmPaketTipi	=sx126x_set_pkt_type(&myLoRa, SX126X_PKT_TYPE_LORA);
		sx126x_get_busy(&myLoRa);

	/* LoRa modülasyon parametrelerini ayarla */
		sx126x_mod_params_lora_t modPar;
			modPar.bw		=SX126X_LORA_BW_125;
			modPar.cr		=SX126X_LORA_CR_4_5;
			modPar.sf		=SX126X_LORA_SF12;
			modPar.ldro		=1;//0: ldr kapalı, 1: ldr açık
		drmModPar		=sx126x_set_lora_mod_params(&myLoRa, &modPar);
		sx126x_get_busy(&myLoRa);

	/* LoRa paket parametrelerini ayarla */
		sx126x_pkt_params_lora_t pktPar;
			pktPar.crc_is_on			=true;
			pktPar.header_type			=SX126X_LORA_PKT_EXPLICIT;
			pktPar.pld_len_in_bytes		=4;
			pktPar.preamble_len_in_symb	=8;
			pktPar.invert_iq_is_on		=false;
		drmPktPar		=sx126x_set_lora_pkt_params(&myLoRa, &pktPar);
		sx126x_get_busy(&myLoRa);

	/* buffer base adres */
		sx126x_set_buffer_base_address(&myLoRa, 0x00, 0x00);
		sx126x_get_busy(&myLoRa);

    /* PA (Power Amplifier) konfigürasyonu */
		sx126x_pa_cfg_params_t pa_pwr_cfg;  //Table 13-21: PA Operating Modes with Optimal Settings
			pa_pwr_cfg.device_sel=0;
			pa_pwr_cfg.hp_max=0x07;
			pa_pwr_cfg.pa_duty_cycle=0x04;
			pa_pwr_cfg.pa_lut=0x01;
		sx126x_set_pa_cfg(&myLoRa, &pa_pwr_cfg);
		sx126x_get_busy(&myLoRa);

    /* TX parametrelerini ayarla */
    	drmTXprm		=sx126x_set_tx_params(&myLoRa, 22, SX126X_RAMP_200_US);
    	sx126x_get_busy(&myLoRa);

    /* IRQ parametrelerini ayarla */
    	sx126x_set_dio_irq_params(&myLoRa,
    		SX126X_IRQ_TX_DONE | SX126X_IRQ_RX_DONE|SX126X_IRQ_PREAMBLE_DETECTED, 	// Hangi olaylar için kesme yapılacağı
			SX126X_IRQ_PREAMBLE_DETECTED,               			// DIO1 pinine atanacak kesme tipi
			SX126X_IRQ_NONE,               				// DIO2 pinine atanacak kesme tipi
			SX126X_IRQ_NONE                   			// DIO3 pinine atanacak kesme tipi (kullanılmıyorsa NONE olarak bırakılır)
    	);
    	
    	sx126x_get_busy(&myLoRa);

    	SetRxTxFallBack(RXTX_BACK_RC);
	//sx126x_clear_irq_status( &myLoRa, SX126X_IRQ_ALL );
    /* Modül hazır */
}

aşağıdaki kodlar da modlar arası geçiş yapmaya çalıştığım komutlar.

sx126x_set_standby(&myLoRa, SX126X_STANDBY_CFG_RC);
	  sx126x_get_busy(&myLoRa);
	  sx126x_get_pkt_type(&myLoRa, &pkt_type);
	  sx126x_get_status(&myLoRa, &radio_status);
	  HAL_Delay(2000);

	  HAL_GPIO_WritePin(GPIOD, GPIO_PIN_12, 0);
	  HAL_GPIO_WritePin(GPIOD, GPIO_PIN_13, 1);
	  sx126x_set_dio_irq_params(&myLoRa, SX126X_IRQ_TX_DONE|SX126X_IRQ_TIMEOUT, SX126X_IRQ_TX_DONE|SX126X_IRQ_TIMEOUT, SX126X_IRQ_NONE, SX126X_IRQ_NONE);
	  drmWriteBuffer=sx126x_write_buffer(&myLoRa, 0, sendData, 4);
	  sx126x_get_busy(&myLoRa);
	  sx126x_set_buffer_base_address(&myLoRa, 0x00, 0x00);
	  drmSetTX=sx126x_set_tx(&myLoRa, 3000); //drmSetTX=sx126x_set_tx_infinite_preamble(&myLoRa);//drmSetTX=sx126x_set_tx_with_timeout_in_rtc_step(&myLoRa, 500);
	  sx126x_get_busy(&myLoRa);
	  sx126x_get_pkt_type(&myLoRa, &pkt_type);
	  sx126x_get_status(&myLoRa, &radio_status);
	  HAL_Delay(2000);

	  HAL_GPIO_WritePin(GPIOD, GPIO_PIN_12, 1);
	  HAL_GPIO_WritePin(GPIOD, GPIO_PIN_13, 0);
	  sx126x_set_dio_irq_params(&myLoRa, SX126X_IRQ_RX_DONE|SX126X_IRQ_CRC_ERROR|SX126X_IRQ_TIMEOUT, SX126X_IRQ_RX_DONE|SX126X_IRQ_CRC_ERROR|SX126X_IRQ_TIMEOUT, SX126X_IRQ_NONE, SX126X_IRQ_NONE);
	  sx126x_set_buffer_base_address(&myLoRa, 0x00, 0x00);
	  drmSetRX = sx126x_set_rx_with_timeout_in_rtc_step(&myLoRa, SX126X_RX_CONTINUOUS );
	  sx126x_get_busy(&myLoRa);
	  sx126x_get_pkt_type(&myLoRa, &pkt_type);
	  sx126x_get_status(&myLoRa, &radio_status);
	  HAL_Delay(2000);

	  HAL_GPIO_WritePin(GPIOD, GPIO_PIN_12, 1);
	  HAL_GPIO_WritePin(GPIOD, GPIO_PIN_13, 1);
	  drmSetRX=sx126x_set_sleep(&myLoRa, SX126X_SLEEP_CFG_WARM_START);// SX126X_SLEEP_CFG_WARM_START//drmSetRX=sx126x_set_fs(&myLoRa);
	  //sx126x_get_status(&myLoRa, &radio_status);
	  HAL_Delay(2000);

gözünüze çarpan bir eksiklik varsa bana söyleyebilir misiniz? İlginiz için şimdiden teşekkür ederim.

**Comment by haluks** [comment]
Merhaba,
Lorayı kullanmak için ilk araştırmaya başladığımda bazı örnekleri kontrol
ettim ufak farklar dışında benzer diyebilirim. Şu anda aktif olarak
kullanıyorum ve bir sıkıntı olmadığından kendi başlatma ayarlarımı doğru
kabul edeceğim. İlk olarak  Loranın çalışması için gerekli ayarları önceden
struct içine kaydediyorum. sx_config fonksiyonu bunu yapıyor burada sadece
değişkene atama var. Modüle bir kayıt yok. MCU ve modül arası pinleri
ayarlıyorum. Modul_IO reset ve busy pinlerinin bağlı olduğu MCU pinlerini
giriş-çıkış ayarlamasını yapıyor. Modul begin pinleri giriş-çıkışı kesme
bağlı olan pinleri ayarlıyor ve modülü resetliyor. SPI iletişimini başlatıp
TCXO oln bir modül için kalibrasyon yapıyorum. Siz hangi marka modeli
kullanıyorsunuz bilmiyorum ama TCXO olan bir modülse ilk önce bu yapılmalı
sizde bu yok. if(tcxo==1) altında yer alan işlemler yapılmalı. TCXO yoksa
stdby_rc ye geçilmeli sizde o şekilde yapılmış. Bir de her adımda busy
kontrolü gerekmiyor. Sonraki adımlar regülatör ve frekans ayarı sizdeki gib
olacak. Yine kullandığınız modüle bağlı olarak frekans sınırları var. Ben
SX1268 olan bir modül kullandığım için 433 MHz seçilidir. Lora modülasyonu
için paket tipi lora seçili ve bu adımdan sonra yukarıda kaydedilen
modulasyon ve paket parametreleri komut olarak yazılır. Sizde de aynısı
yapılmış. Sonraki adımda yine modüle bağlı olarak bir fark var. Bende rf
switch için iki adet pin var RX ve TX pinleri. Bunlar anten gücünü
ayarlamak için kullanılıyor. Dio2 pini kesme kaynağı olarak kullanmak
yerine rf switch için kullanılıyor. Sonraki adım yine farklı sizde kesme
pinlerinin ayarları yapılmamış. Bu aşamada kesmelerin kapalı olarak
ayarlanması daha doğru olur. Bir farkta rx ve tx sonrası dönüş ayarı da
burada yapılmamış. Ben bu sıralamayı datasheette verilen rx ve tx
sıralamasının ortak kısımlarını alarak yaptım. Sizin yaptığınız yanlış
diyemem. Rx için yanlış ama Tx için doğrudur. TX ayarlamanız sonrası OCP
registeri ayarlamanız ve datasheet bahsedilen tx clamp(15.2.2)
ayarlamanız uygun olur. Rx ile ilgili birkaç ayarlamayı da yapmamışsınız.
Modlar arası geçişte 12 ve 13 pinleri sanırım rx tx rf switch pinleridir.
dio2 ile tx bağlantısı yaparsanız modül tx anında kendi otomatik geçer
böylece istenen güce ulaşır.
Tx için drmWriteBuffer=sx126x_write_buffer(&myLoRa, 0, sendData, 4);
satırında belleğe gidecek veri yazılmış ama alt satırda adres sıfırlanmış.
Bunu yapmayın zaten bellek işaretçisi otomatik artar veri gidince ya da
tekrar belleğe yazmadan önce bunu yapın.
İyi çalışmalar..

ademgolcuk42 ***@***.***>, 3 Kas 2024 Paz, 14:23 tarihinde
şunu yazdı:

**Comment by ademgolcuk42** [comment]
Çok teşekkür ederim. Problem çözüldü sayenizde.

**Comment by haluks** [comment]
Rica ederim, sorunun çözülmesine sevindim.

ademgolcuk42 ***@***.***>, 4 Kas 2024 Pzt, 14:45 tarihinde
şunu yazdı:
